# Imagem Docker
image:
  file: .gitpod.Dockerfile

# Portas e Ações
ports:
  - name: Jasmine + Karma no Angular
    description: App com testes
    port: 4200
    onOpen: open-browser
    visibility: public

# Tarefas na Inicialização
tasks:
  - before: export NG_CLI_ANALYTICS=ci
  - init: echo n | npm i -g @angular/cli
  - command: >
      cd jasmine-karma-angular &&
      npm i &&
      npm run start

# Github
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false
    addLabel: false

vscode:
  extensions:
    - hbenl.vscode-jasmine-test-adapter
    - EditorConfig.EditorConfig
    - dbaeumer.vscode-eslint
    - Tobermory.es6-string-html
    - prantlf.karma-problem-matchers
    - DavidAnson.vscode-markdownlint
    - rvest.vs-code-prettier-eslint
    - esbenp.prettier-vscode
    - SonarSource.sonarlint-vscode
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
    - shardulm94.trailing-spaces
    - vscode-icons-team.vscode-icons
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-portuguese-brazilian
    - formulahendry.auto-rename-tag
    - formulahendry.auto-close-tag
